### ISSUE TITLE
Unexpected Barcode Assignment Imbalance with SeqTagger on RNA004 Dataset

### ISSUE THREAD

**Issue by BrendanBeahan** [novoalab/SeqTagger#2]
Hi @lpryszcz 

I have attempted to run SeqTagger on an IVT RNA004 dataset we generated in-house. For this dataset, we created four equal samples, each assigned one of the four DeePlexiCon barcodes. These barcodes appear to be the same as those used for SeqTagger.

However, when running SeqTagger, I observed assignment amounts that differ significantly from what I expected.

![image](https://github.com/user-attachments/assets/9ef83acd-ad3d-412e-a6d5-4c95ac04c4a1)

I anticipated a roughly equal distribution of barcode assignments, which I successfully achieved previously using the RNA002 dataset with DeePlexiCon.

The wet lab report regarding the data and input sample amounts seemed sound. Do you have any insights or suggestions about what might be causing this discrepancy? 

Best,
Brendan

**Comment by enovoa** [comment]
Hi @BrendanBeahan, just to add that it could be that the barcodes were not perfectly balanced at the library prep step, either due to overestimation of cDNA product from unligated adapters, or from other sources, so unrelated to SeqTagger itself.  In this regard, Seqtagger works with RNA002 as well as with RNA004, so you can try your older RNA002 runs with Seqtagger to check that Seqtagger is working properly in those runs or not. 
Best
Eva

**Comment by BrendanBeahan** [comment]
Hi @enovoa,

Indeed SeqTagger looks to have successfully recapitulated roughly equal results for my RNA002 dataset.

**Comment by lpryszcz** [comment]
I don't see anything odd above. If it works well with RNA002, I'd suspect your latest RNA004 run isn't well balanced.
